DATA_PATH: 'data/'
LLM: 'starling-lm:7b-alpha-q5_K_M'
OLLAMA_BASE_URL: ''
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
WEAVIATE_URL: 'http://localhost:8080'
INDEX_NAME: 'Sparrow'
CHUNK_SIZE: 1000
