---
version: '3.4'
services:
  llm-service:
    container_name: llm-service
    image: docker.io/library/llamaindex-rag:v1 
    # llm-service port is 5000
    network_mode: host
    # ports:
    #   - 5000:5000
    volumes:
      - ./data:/app/data
      - ./config.yml:/app/config.yml
    depends_on:
      - weaviate

  weaviate:
    container_name: weaviate-db
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.22.4
    network_mode: host
    # ports:
    # - 8080:8080
    # - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
...