from flask import Flask, request
import timeit
from rag.pipeline import build_rag_pipeline


app = Flask(__name__)

rag_chain = build_rag_pipeline()


def get_rag_response(query):
    """
    Queries the RAG pipeline with the provided query and retrieves the generated response.

    Args:
        query: The textual query to be submitted to the RAG pipeline.
        rag_chain: The pre-built RAG pipeline object for processing the query.

    Returns:
        The response text generated by the RAG pipeline based on the input query.

    """
    result = rag_chain.query(query)
    return result


@app.route('/chat', methods=['GET'])
def chat():
    prompt = request.args.get('prompt')

    if prompt is not None:
        print('Retrieving answer...')
        answer = get_rag_response(prompt)
        answer = str(answer).strip()
        print('answer is: ' + answer)
        return answer, 200
    else:
        return "error", 400




# 启动开发服务器（调试模式）
if __name__ == '__main__':
    app.run(debug=True)